/**
 * Build the distributable archives of this bundle.
 *
 *   node _pack.mjs   -> dist/dsh-cds-mode-<version>.zip   (distribution platforms)
 *                    -> dist/dsh-cds-mode-<version>.tgz   (npm/pnpm layout)
 *
 * Both carry the identical file set under a `package/` top level, so one
 * extraction layout serves either archive. `.zip` is generated by this
 * package's own dependency-free writer (`_zip.mjs`) and then read back with a
 * system extractor — a self-written writer is not trusted without that check.
 *
 * Steps: sync the bundled corpus, verify it, run both verifiers, self-check the
 * file list, build both archives, extract and byte-compare each. Any failure
 * aborts — a package that fails its own checks is never emitted.
 */

import { execFileSync } from 'node:child_process'
import { createHash } from 'node:crypto'
import { existsSync, mkdirSync, readdirSync, readFileSync, rmSync, statSync, writeFileSync } from 'node:fs'
import { dirname, join, relative } from 'node:path'
import { fileURLToPath } from 'node:url'
import { makeZip } from './_zip.mjs'

const PKG = dirname(fileURLToPath(import.meta.url))
const manifest = JSON.parse(readFileSync(join(PKG, 'package.json'), 'utf8'))
const DIST = join(PKG, 'dist')
const STAGE = join(DIST, 'package')
const BASE = `${manifest.name.replace('/', '-').replace('@', '')}-${manifest.version}`
const TGZ = join(DIST, `${BASE}.tgz`)
const ZIP = join(DIST, `${BASE}.zip`)

const run = (label, cmd, args) => {
  process.stdout.write(`\n▸ ${label}\n`)
  try {
    execFileSync(cmd, args, { stdio: 'inherit', cwd: PKG })
  } catch {
    console.error(`\n[pack] 失败于：${label}`)
    process.exit(1)
  }
}

// ── 1. Sync + verify the bundled corpus ─────────────────────────────────────
run('同步内置语料', process.execPath, ['_sync-corpus.mjs'])
run('校验内置语料与源一致', process.execPath, ['_sync-corpus.mjs', '--check'])

// ── 2. Run both verifiers ───────────────────────────────────────────────────
run('校验 1/2：插件与预设', process.execPath, ['_verify3.mjs'])
run('校验 2/2：语料与委任书', process.execPath, ['_verify-corpus.mjs'])

// ── 3. Resolve the shipping file list ───────────────────────────────────────
/** Expand this package's `files` patterns into a concrete, sorted list. */
function shipList() {
  const patterns = manifest.files ?? []
  const out = new Set()

  const walk = (dir) => {
    for (const name of readdirSync(dir).sort()) {
      const full = join(dir, name)
      const rel = relative(PKG, full).split('\\').join('/')
      if (name === 'node_modules' || name === 'dist' || rel.startsWith('.')) continue
      if (statSync(full).isDirectory()) walk(full)
      else out.add(rel)
    }
  }
  // A pattern without a wildcard is a file or a directory prefix; with a
  // wildcard it is matched against the flat relative path.
  const flat = []
  const collect = (dir) => {
    for (const name of readdirSync(dir).sort()) {
      const full = join(dir, name)
      const rel = relative(PKG, full).split('\\').join('/')
      if (name === 'node_modules' || name === 'dist' || name.startsWith('.')) continue
      if (statSync(full).isDirectory()) collect(full)
      else flat.push(rel)
    }
  }
  collect(PKG)

  const keep = new Set()
  for (const p of patterns) {
    if (p.includes('*')) {
      const re = new RegExp('^' + p.replace(/[.+^${}()|[\]\\]/g, '\\$&').replace(/\*\*/g, '.*').replace(/\*/g, '[^/]*') + '$')
      for (const f of flat) if (re.test(f)) keep.add(f)
    } else if (flat.includes(p)) {
      keep.add(p)
    } else {
      for (const f of flat) if (f.startsWith(p.replace(/\/$/, '') + '/')) keep.add(f)
    }
  }
  return [...keep].sort()
}

const files = shipList()
if (files.length === 0) {
  console.error('[pack] files 解析为空，拒绝打包')
  process.exit(1)
}

// ── 3b. 清单自检：必须带上语料 ─────────────────────────────────────────────
// 曾经漏过：`cds/**/*.md` 不匹配根级文件，于是 CORE.md / README.md / CHANGELOG.md
// 没进包，装完直接「内置语料缺失」。这几条断言把它变成硬门禁。
// 注意：`package.json` 由 npm/tar 布局惯例自动带上，不列在这里——最终由 3c 从
// 真实 tarball 里核对。
const MUST_HAVE = [
  'README.md',
  'INSTALL.md',
  'LICENSE',
  'index.js',
  'cordis.patch.yml',
  'icon.svg',
  // Dev/verify scripts the README tells readers to run. They depend on each
  // other (`_pack` -> `_sync-corpus` + `_zip`; `_verify3` -> `_patch-reader`),
  // so the whole group has to ship.
  '_verify3.mjs',
  '_verify-corpus.mjs',
  '_pack.mjs',
  '_zip.mjs',
  '_sync-corpus.mjs',
  '_patch-reader.mjs',
  '_check-specs.mjs',
  '_compare-extract.mjs',
  'cds/CORE.md',
  'cds/README.md',
  'cds/CHANGELOG.md',
  'cds/personas/chen.md',
  'cds/personas/A1-官方派调查者.md',
  'cds/personas/E3-宣传片视频.md',
  'cds/protocol/peer-channel.md',
  'cds/protocol/artifacts.md',
  'cds/protocol/bug-taxonomy.md',
  'cds/questions/99-adaptive-asking.md',
  'cds/workflow/01-new-project.md',
  'cds/selfrescue/cache-economy.md',
  'cds/templates/state.json',
  'cds/templates/state.md',
]
const absent = MUST_HAVE.filter((f) => !files.includes(f))
if (absent.length > 0) {
  console.error('[pack] 清单缺少必需文件，拒绝打包：')
  for (const f of absent) console.error('  ' + f)
  console.error('  检查 package.json 的 files 字段（注意 glob 的层级限制）。')
  process.exit(1)
}
console.log(`\n▸ 清单自检：${MUST_HAVE.length} 项必需文件齐全`)

// ── 3c. 全覆盖检查：cds/ 下的语料一个都不许漏 ────────────────────────────────
// 18 项定点检查会漏掉**整类**文件。这里按目录全量比对。
// 曾经两次踩到自制 glob 的层级限制：`cds/**/*.md` 不匹配根级，且把
// `cds/**/*.md` 翻成 `.*/`（不含 `/`）导致只能匹配一级子目录。
const listAll = (dir, base = dir, out = []) => {
  for (const n of readdirSync(dir).sort()) {
    const full = join(dir, n)
    if (statSync(full).isDirectory()) listAll(full, base, out)
    else out.push(relative(base, full).split('\\').join('/'))
  }
  return out
}
const corpusOnDisk = listAll(join(PKG, 'cds')).map((f) => 'cds/' + f)
const corpusMissing = corpusOnDisk.filter((f) => !files.includes(f))
if (corpusMissing.length > 0) {
  console.error(`\n[pack] 清单漏掉 ${corpusMissing.length} 个语料文件，拒绝打包（前 10 个）：`)
  for (const f of corpusMissing.slice(0, 10)) console.error('  ' + f)
  console.error('  检查 package.json 的 files 字段：glob 每个 * 只匹配一层目录。')
  process.exit(1)
}
console.log(`▸ 语料全覆盖检查：cds/ 下 ${corpusOnDisk.length} 个文件全部在清单内`)

// ── 4. Stage under dist/package/ ────────────────────────────────────────────
if (existsSync(DIST)) rmSync(DIST, { recursive: true, force: true })
mkdirSync(STAGE, { recursive: true })
for (const rel of files) {
  const dest = join(STAGE, rel)
  mkdirSync(dirname(dest), { recursive: true })
  writeFileSync(dest, readFileSync(join(PKG, rel)))
}

// ── 5. Tar (npm layout: entries under package/) ─────────────────────────────
// `package.json` is listed in `files` on purpose: we build the tarball with
// `tar` from an explicit whitelist, so nothing is added implicitly the way
// `npm pack` would add the manifest.
run('打包 tarball', 'tar', ['-czf', TGZ, '-C', DIST, 'package'])

// ── 5a. ZIP, from the SAME verified file list ───────────────────────────────
// Distribution platforms often want `.zip`. `.zip` is a different format from
// `.tgz` — not a rename — so we write it with our own dependency-free writer.
// Entries keep the npm `package/` prefix, identical to the tarball, so one
// extraction layout serves both.
const zipEntries = [
  { name: 'package/', data: Buffer.alloc(0), isDir: true },
  ...files.map((rel) => ({ name: 'package/' + rel, data: readFileSync(join(PKG, rel)) })),
]
writeFileSync(ZIP, makeZip(zipEntries.filter((e) => !e.isDir)))
console.log(`\n▸ 打包 zip：${files.length} 个条目，与 tarball 同源`)

// ── 5b. 解压后核对（权威检查）─────────────────────────────────────────────
// 不用 `tar -tzf` 的列表：中文文件名经 shell 往返会出现显示编码问题，名字比对
// 不可靠。改为**真的解压出来**，再用文件系统逐个核对——顺带证明了包能正常解压。
const VERIFY_DIR = join(DIST, '_verify-extract')
if (existsSync(VERIFY_DIR)) rmSync(VERIFY_DIR, { recursive: true, force: true })
mkdirSync(VERIFY_DIR, { recursive: true })
run('解压核对（tar）', 'tar', ['-xzf', TGZ, '-C', VERIFY_DIR])

const EXTRACTED = join(VERIFY_DIR, 'package')
const problems = []
for (const f of [...MUST_HAVE, 'package.json']) {
  if (!existsSync(join(EXTRACTED, f))) problems.push('缺 ' + f)
}
// 语料文件总数必须与源一致（防止 glob 又漏掉某一类）
const countFiles = (dir, n = { c: 0 }) => {
  for (const e of readdirSync(dir)) {
    const full = join(dir, e)
    if (statSync(full).isDirectory()) countFiles(full, n)
    else n.c++
  }
  return n.c
}
const srcCorpusCount = countFiles(join(PKG, 'cds'))
const tarCorpusCount = countFiles(join(EXTRACTED, 'cds'))
if (srcCorpusCount !== tarCorpusCount) {
  problems.push(`语料文件数不符：源 ${srcCorpusCount} / 包内 ${tarCorpusCount}`)
}
if (problems.length > 0) {
  console.error('\n[pack] 解压核对失败，产物不可用：')
  for (const p of problems) console.error('  ' + p)
  rmSync(TGZ, { force: true })
  rmSync(ZIP, { force: true })
  rmSync(VERIFY_DIR, { recursive: true, force: true })
  console.error('  已删除产物，避免发出坏包。')
  process.exit(1)
}
console.log(`\n▸ 解压核对（tar）：必需文件齐全，语料 ${tarCorpusCount} 个文件与源一致`)
rmSync(VERIFY_DIR, { recursive: true, force: true })

// ── 5c. 解压核对 zip（独立验证，别信自己的写入器）─────────────────────────
// 我们的 zip 是手写的，所以必须**用系统的解压器读回来**才算验证过。
const ZIP_VERIFY = join(DIST, '_verify-zip')
if (existsSync(ZIP_VERIFY)) rmSync(ZIP_VERIFY, { recursive: true, force: true })
mkdirSync(ZIP_VERIFY, { recursive: true })
run('解压核对（zip）', 'tar', ['-xf', ZIP, '-C', ZIP_VERIFY])

const zipExtracted = join(ZIP_VERIFY, 'package')
const zipProblems = []
for (const f of [...MUST_HAVE, 'package.json']) {
  if (!existsSync(join(zipExtracted, f))) zipProblems.push('缺 ' + f)
}
const zipCorpusCount = countFiles(join(zipExtracted, 'cds'))
if (zipCorpusCount !== srcCorpusCount) {
  zipProblems.push(`语料文件数不符：源 ${srcCorpusCount} / zip 内 ${zipCorpusCount}`)
}
// 逐字节比对 zip 与 staging：证明两种格式内容完全一致
let zipDiff = 0
for (const rel of files) {
  const a = readFileSync(join(PKG, rel))
  const bPath = join(zipExtracted, rel)
  if (!existsSync(bPath) || !a.equals(readFileSync(bPath))) zipDiff++
}
if (zipDiff > 0) zipProblems.push(`与源逐字节不一致的文件数：${zipDiff}`)
if (zipProblems.length > 0) {
  console.error('\n[pack] zip 解压核对失败，产物不可用：')
  for (const p of zipProblems) console.error('  ' + p)
  rmSync(ZIP, { force: true })
  rmSync(ZIP_VERIFY, { recursive: true, force: true })
  console.error('  已删除该 zip，避免发出坏包。')
  process.exit(1)
}
console.log(`▸ 解压核对（zip）：系统解压器读回成功，${files.length} 个文件与源逐字节一致`)
rmSync(ZIP_VERIFY, { recursive: true, force: true })

const bytes = statSync(TGZ).size
const zipBytes = statSync(ZIP).size
const sha = createHash('sha256').update(readFileSync(TGZ)).digest('hex')
const zipSha = createHash('sha256').update(readFileSync(ZIP)).digest('hex')
const totalRaw = files.reduce((n, f) => n + statSync(join(PKG, f)).size, 0)

console.log(`\n${'─'.repeat(64)}`)
console.log(`包名    : ${manifest.name}@${manifest.version}`)
console.log(`文件数  : ${files.length}（原始 ${(totalRaw / 1024).toFixed(0)} KB）`)
console.log(`ZIP     : ${ZIP}`)
console.log(`          ${(zipBytes / 1024).toFixed(0)} KB  sha256 ${zipSha}`)
console.log(`TGZ     : ${TGZ}`)
console.log(`          ${(bytes / 1024).toFixed(0)} KB  sha256 ${sha}`)
console.log(`${'─'.repeat(64)}`)
console.log('两者内容相同，只有压缩格式不同：')
console.log('  .zip  —— 给分发/上传平台')
console.log('  .tgz  —— 给 npm/pnpm 与 install_bundle 的 tarball 路径')

console.log('\n安装（对方机器）：')
console.log(`  1) 解压 ${BASE}.zip（或 .tgz），得到 package/ 目录`)
console.log('  2) 在 DSH 会话里：')
console.log('     plugin_manager  action: install_bundle  target: <解压出的 package 目录绝对路径>')
console.log('  3) 重启 dsh web，新开会话，预设选「CDS 模式」或「CDS 模式 · 同伴频道版」')
console.log('\n注意：install_bundle 接受 registry 包 / git 地址 / tarball / 绝对路径，')
console.log('      不接受 .zip 本身。zip 是给平台分发的，对方需先解压。')
